import { LandingSite, RegionId } from './types';

export const REGION_LABEL: Record<RegionId, string> = {
  mombasa: 'Mombasa',
  north: 'North coast',
  south: 'South coast',
};

export const LANDING_SITES: LandingSite[] = [
  {
    id: 'old-port',
    name: 'Old Port',
    county: 'Mombasa',
    region: 'mombasa',
    lat: -4.0617,
    lon: 39.6794,
  },
  {
    id: 'mkomani',
    name: 'Mkomani',
    county: 'Mombasa',
    region: 'mombasa',
    lat: -4.043,
    lon: 39.668,
  },
  {
    id: 'nyali',
    name: 'Nyali',
    county: 'Mombasa',
    region: 'mombasa',
    lat: -4.049,
    lon: 39.706,
  },
  {
    id: 'bamburi',
    name: 'Bamburi',
    county: 'Mombasa',
    region: 'mombasa',
    lat: -4.001,
    lon: 39.732,
  },
  {
    id: 'mtwapa',
    name: 'Mtwapa',
    county: 'Kilifi',
    region: 'mombasa',
    lat: -3.95,
    lon: 39.745,
  },
  {
    id: 'likoni',
    name: 'Likoni',
    county: 'Mombasa',
    region: 'south',
    lat: -4.09,
    lon: 39.661,
  },
  {
    id: 'diani',
    name: 'Diani / Ukunda',
    county: 'Kwale',
    region: 'south',
    lat: -4.28,
    lon: 39.587,
  },
  {
    id: 'gazi',
    name: 'Gazi',
    county: 'Kwale',
    region: 'south',
    lat: -4.424,
    lon: 39.505,
  },
  {
    id: 'msambweni',
    name: 'Msambweni',
    county: 'Kwale',
    region: 'south',
    lat: -4.472,
    lon: 39.482,
  },
  {
    id: 'shimoni',
    name: 'Shimoni',
    county: 'Kwale',
    region: 'south',
    lat: -4.647,
    lon: 39.381,
    watch: 'dolphins',
  },
  {
    id: 'vanga',
    name: 'Vanga',
    county: 'Kwale',
    region: 'south',
    lat: -4.663,
    lon: 39.218,
  },
  {
    id: 'kilifi',
    name: 'Kilifi',
    county: 'Kilifi',
    region: 'north',
    lat: -3.633,
    lon: 39.85,
  },
  {
    id: 'watamu',
    name: 'Watamu',
    county: 'Kilifi',
    region: 'north',
    lat: -3.354,
    lon: 40.021,
    watch: 'dolphins',
  },
  {
    id: 'malindi',
    name: 'Malindi',
    county: 'Kilifi',
    region: 'north',
    lat: -3.219,
    lon: 40.127,
  },
  {
    id: 'ngomeni',
    name: 'Ngomeni',
    county: 'Kilifi',
    region: 'north',
    lat: -3.0,
    lon: 40.2,
  },
  {
    id: 'kipini',
    name: 'Kipini',
    county: 'Tana River',
    region: 'north',
    lat: -2.527,
    lon: 40.526,
  },
  {
    id: 'lamu',
    name: 'Lamu',
    county: 'Lamu',
    region: 'north',
    lat: -2.272,
    lon: 40.902,
  },
];

export function siteById(id: string): LandingSite | undefined {
  return LANDING_SITES.find((site) => site.id === id);
}
